[project]
name = "genept-tools"
version = "0.1.0"
description = "Your project description"
dependencies = [
    "anndata",
    "boto3",
    "datasets",
    "lightgbm",
    "nbformat",
    "numpy",
    "openai",
    "pandas",
    "scanpy",
    "scikit-learn",
    "umap-learn",
]

[project.optional-dependencies]
dev = [
    "matplotlib",
    "seaborn",
    "black[jupyter]",
    "isort",
    "ipykernel",
    "pip-tools",
    "plotly",
    "pytest",
]

with_torch = [
    "torch==2.4.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

[tool.black]
line-length = 88
target-version = ["py39"]

[tool.isort]
profile = "black"
multi_line_output = 3 
skip = [".gitignore", ".dockerignore"]