[project]
name = "genept-tools"
version = "0.1.0"
description = "Your project description"
requires-python = ">=3.10"
dependencies = [
    "anndata",
    "anndata-metadata>=0.1.2",
    "boto3",
    "datasets",
    "h5py>=3.13.0",
    "ipykernel",
    "lightgbm",
    "nbformat",
    "networkx",
    "numpy",
    "obonet",
    "onclass @ git+https://github.com/wangshenguiuc/OnClass.git",
    "openai",
    "optuna",
    "pandas",
    "plotly",
    "pulp>=3.1.1",
    "python-dotenv>=1.1.0",
    "s3fs>=0.4.2",
    "scanpy",
    "scikit-learn",
    "torch>=2.1.2",
    "umap-learn",
    "wandb>=0.20.1",
    "xgboost>=3.0.1",
]

[dependency-groups]
dev = [
    "matplotlib",
    "nbdime",
    "seaborn",
    "black[jupyter]",
    "duckdb",
    "isort",
    "ipykernel",
    "jupyterlab",
    "pip-tools",
    "plotly",
    "pytest>=8.1.1,<9",
    "pytest-env",
    "pytest-xdist",
    "ruff",
    "yapf==0.40.2",
]

[tool.pytest.ini_options]
addopts = "-v --ignore=.venv --ignore=__pycache__ -W ignore::DeprecationWarning"
testpaths = ["test"]
python_files = ["test_*.py"]
norecursedirs = [
    ".*",
    "__pycache__",
    "*.egg",
    ".eggs",
    "*.egg-info",
    "dist",
    "build",
    ".env",
    ".venv",
    "venv",
    "env",
    "docs"
]
filterwarnings = [
    "ignore:Transforming to str index:anndata._core.aligned_df.ImplicitModificationWarning",
]

[tool.yapf]
based_on_style = "yapf"
column_limit = 88
continuation_indent_width = 2
indent_width = 2


[tool.isort]
profile = "black"
multi_line_output = 3 
skip = [".gitignore", ".dockerignore"]
